ALTER TABLE `alive_ip` CHANGE `datetime` `created_at` INT(11) NOT NULL;
ALTER TABLE `announcement` CHANGE `date` `created_at` INT NOT NULL;
ALTER TABLE `announcement` ADD `updated_at` INT NOT NULL AFTER `created_at`;
ALTER TABLE `coupon` ADD `created_at` INT NOT NULL AFTER `total_use_count`, ADD `updated_at` INT NOT NULL AFTER `created_at`;
ALTER TABLE `email_queue` CHANGE `time` `created_at` INT(11) NOT NULL;
ALTER TABLE `detect_log` CHANGE `datetime` `created_at` INT(11) NOT NULL;
ALTER TABLE `node_info` CHANGE `log_time` `created_at` INT(11) NOT NULL;
ALTER TABLE `node_online_log` CHANGE `log_time` `created_at` INT(11) NOT NULL;
ALTER TABLE `order` CHANGE `created_time` `created_at` INT(11) NOT NULL COMMENT '订单创建时间';
ALTER TABLE `order` CHANGE `updated_time` `updated_at` INT(11) NOT NULL COMMENT '订单更新时间';
ALTER TABLE `order` CHANGE `expired_time` `expired_at` INT(11) NULL DEFAULT NULL COMMENT '订单失效时间';
ALTER TABLE `order` CHANGE `paid_time` `paid_at` INT(11) NULL DEFAULT NULL COMMENT '订单支付时间';
RENAME TABLE `zero`.`payback` TO `zero`.`commission`;
ALTER TABLE `commission` CHANGE `ref_get` `get_amount` DECIMAL(12,2) NOT NULL COMMENT '获得佣金';
ALTER TABLE `commission` CHANGE `total` `order_amount` DECIMAL(12,2) NOT NULL COMMENT '订单金额';
ALTER TABLE `commission` CHANGE `ref_by` `order_no` VARCHAR(30) NOT NULL COMMENT '订单号';
ALTER TABLE `commission` CHANGE `datetime` `created_at` INT(11) NOT NULL;
ALTER TABLE `commission` ADD `invite_userid` INT NOT NULL AFTER `userid`;
ALTER TABLE `signin_ip` CHANGE `datetime` `created_at` INT(11) NOT NULL;
ALTER TABLE `user_subscribe_log` CHANGE `request_time` `created_at` INT(11) NOT NULL COMMENT '请求时间';
ALTER TABLE `user_token` CHANGE `create_time` `created_at` INT(11) NOT NULL;
ALTER TABLE `user_token` CHANGE `expire_time` `expired_at` INT(11) NOT NULL;
ALTER TABLE `user_traffic_log` CHANGE `datetime` `created_at` INT(11) NOT NULL COMMENT '记录时间';
ALTER TABLE `withdraw_log` CHANGE `datetime` `created_at` INT(11) NULL DEFAULT NULL;
ALTER TABLE `ticket` CHANGE `datetime` `created_at` INT(11) NOT NULL COMMENT '创建时间';
ALTER TABLE `ticket` CHANGE `updated_at` `updated_at` INT(11) NOT NULL COMMENT '更新时间';